defaults:
  - override hydra/launcher: joblib
    
seed: 42
train_test_ratio: 0.7
CCA_dim: 512 # dimension of the CCA transformation
sim_dim: 10 # dimension of the similarity score
equal_weights: False
audio_encoder: "clap"
text_encoder: "gtr"
paths:
  repo_root: "/home/pl22767/Project/MMDA/"
  dataset_path: "/nas/pohan/datasets/MusicCaps/"
  save_path: ${paths.dataset_path}embeddings/
  plots_path: ${paths.repo_root}plots/MusicCaps/

hydra:
  run:
    dir: ${paths.repo_root}hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}