defaults:
  - override hydra/launcher: joblib
hydra:
  run:
    dir: hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 42
train_test_ratio: 0.7
CCA_dim: 700 # dimension of the CCA transformation
sim_dim: 700 # dimension of the similarity score
equal_weights: True
img_encoder: "clip"
text_encoder: "gtr"
paths:
  repo_root: "/home/po-han/Desktop/Projects/TIFE/"
  # sop_dataset_path: "/nas/omama/datasets/Stanford_Online_Products/"
  sop_dataset_path: "/home/po-han/Downloads/datasets/Stanford_Online_Products/"
  save_path: "/home/po-han/Downloads/SOP/"
  plots_path: ${paths.repo_root}plots/sop/
work_dir: ${paths.repo_root}hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

llava:
  model_path: '/nas/omama/llava-v1.5-13b'
  model_base: null
  num_gpus: 4
  conv_mode: null
  temperature: 0.2
  max_new_tokens: 512
  load_8bit: True
  load_4bit: False
  debug: False
  num_processes: 4
