defaults:
  - override hydra/launcher: joblib
hydra:
  run:
    dir: hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 42
CCA_dim: 700 # dimension of the CCA transformation
sim_dim: 700 # dimension of the similarity score
audio_encoder: "clap"
text_encoder: "gtr"
paths:
  repo_root: "/home/pl22767/Project/TIFE/"
  # repo_root: "/home/po-han/Desktop/Projects/TIFE/"
  dataset_path: "/nas/pohan/datasets/WikiMuTe/"
  save_path: "/nas/tirr/SOP/"
  # save_path: "/home/po-han/Downloads/wikimute/"
  plots_path: ${paths.repo_root}plots/wikimute/
work_dir: ${paths.repo_root}hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

llava:
  model_path: '/nas/omama/llava-v1.5-13b'
  model_base: null
  num_gpus: 4
  conv_mode: null
  temperature: 0.2
  max_new_tokens: 512
  load_8bit: True
  load_4bit: False
  debug: False
  num_processes: 4
