defaults:
  - override hydra/launcher: joblib

seed: 42
train_test_ratio: 0.7
noisy_train_set: True
dataset: "tiil" # imagenet, sop, tiil, or musiccaps
repo_root: "/home/pl22767/Project/MMDA/"

sop:
  CCA_dim: 500 # dimension of the CCA transformation
  sim_dim: 150 # dimension of the similarity score
  # shuffle_level: "dataset" # "obj", "class", or "dataset"
  equal_weights: False
  text_encoder: "gtr"
  img_encoder: "clip"
  paths:
    # repo_root: "/home/po-han/Desktop/Projects/MMDA/"
    dataset_path: "/nas/omama/datasets/Stanford_Online_Products/"
    # dataset_path: "/home/po-han/Downloads/datasets/Stanford_Online_Products/"
    save_path: "/nas/tirr/SOP/"
    # save_path: "/home/po-han/Downloads/SOP/"
    plots_path: ${repo_root}plots/Stanford_Online_Products/
  work_dir: ${repo_root}hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

musiccaps:
  CCA_dim: 512 # dimension of the CCA transformation
  sim_dim: 25 # dimension of the similarity score
  equal_weights: False
  audio_encoder: "clap"
  text_encoder: "gtr"
  paths:
    dataset_path: "/nas/pohan/datasets/MusicCaps/wav_files/"
    save_path: ${musiccaps.paths.dataset_path}embeddings/
    plots_path: ${repo_root}plots/MusicCaps/

imagenet:
  CCA_dim: 750 # dimension of the CCA transformation
  sim_dim: 200 # dimension of the similarity score
  equal_weights: False
  img_encoder: "clip"
  text_encoder: "gtr"
  paths:
    dataset_path: "/nas/pohan/datasets/ImageNet/"
    save_path: ${imagenet.paths.dataset_path}embeddings/
    plots_path: ${repo_root}plots/ImageNet/

tiil:
  CCA_dim: 750 # dimension of the CCA transformation
  sim_dim: 200 # dimension of the similarity score
  equal_weights: False
  img_encoder: "clip"
  text_encoder: "gtr"
  paths:
    dataset_path: "/nas/pohan/datasets/tiil/"
    save_path: ${tiil.paths.dataset_path}embeddings/
    plots_path: ${repo_root}plots/TIIL/

hydra:
  run:
    dir: ${repo_root}hydra/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

llava:
  model_path: '/nas/omama/llava-v1.5-13b'
  model_base: null
  num_gpus: 6
  conv_mode: null
  temperature: 0.2
  max_new_tokens: 512
  load_8bit: True
  load_4bit: False
  debug: False
  num_processes: 6

# Hyperparameters of asif benchmark
asif:
  non_zeros: 800
  val_exps: [8]
  max_gpu_mem_gb: 23