defaults:
  - override hydra/launcher: joblib
hydra:
  run:
    dir: hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 42
img_encoder: "clip"
text_encoder: "clip"
work_dir: ${hydra:runtime.cwd}
root_dir: "/nas/tirr/waterbird/dataset/waterbird_landfraction50_forest2water2/"
save_dir: "/nas/tirr/waterbird/"
data_path: "${work_dir}/data"
