defaults:
  - override hydra/launcher: joblib
hydra:
  run:
    dir: hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 42
img_encoder: "clip"
# text_encoder: "clip"
gt_category: "" # "" or "_bg"
noise_std: 1
work_dir: ${hydra:runtime.cwd}
root_dir: "/nas/tirr/waterbird/waterbird_landfraction50_forest2water2/"
root95_dir: "/nas/tirr/waterbird/waterbird_complete95_forest2water2/"
save_dir: "/nas/tirr/waterbird/"
data_path: "${work_dir}/data"
